# Generated by Django 3.2.5 on 2021-12-17 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリ―')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('shop_name', models.CharField(max_length=30, verbose_name='店の名前')),
                ('catchphrase', models.TextField(verbose_name='キャッチフレーズ')),
                ('postalcode', models.CharField(blank=True, max_length=30, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='住所')),
                ('address_image', models.ImageField(upload_to='media/address', verbose_name='店の地図')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='ホームページURL')),
                ('instagram', models.URLField(blank=True, max_length=250, null=True, verbose_name='インスタグラムURL')),
                ('twitter', models.URLField(blank=True, max_length=250, null=True, verbose_name='ツイッターURL')),
                ('shop_detail', models.TextField(verbose_name='店の詳細')),
                ('opening', models.CharField(blank=True, max_length=250, null=True, verbose_name='営業時間')),
                ('contact', models.CharField(blank=True, max_length=250, null=True, verbose_name='連絡先')),
                ('closed', models.CharField(blank=True, max_length=250, null=True, verbose_name='定休日')),
                ('image', models.ImageField(upload_to='media/image', verbose_name='店の画像')),
                ('in_area_num', models.IntegerField(verbose_name='エリア内番号')),
                ('item_name', models.CharField(max_length=30, verbose_name='物の名前')),
                ('item_detail', models.TextField(verbose_name='物の詳細')),
                ('stamp_image', models.ImageField(upload_to='media/stamp', verbose_name='スタンプ')),
                ('keyword', models.CharField(max_length=30, verbose_name='キーワード')),
                ('origin', models.TextField(verbose_name='由来')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='stamp.category', verbose_name='カテゴリ―')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('judgement', models.BooleanField(blank=True, default=True, verbose_name='判定')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='stamp.shop', verbose_name='店')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='stamp',
            field=models.ManyToManyField(related_name='shops', through='stamp.Stamp', to=settings.AUTH_USER_MODEL, verbose_name='スタンプ'),
        ),
        migrations.AddField(
            model_name='shop',
            name='tags',
            field=models.ManyToManyField(related_name='shops', to='stamp.Tag', verbose_name='タグ'),
        ),
    ]
